#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro")
endif

TOPDIR ?= $(CURDIR)
include $(DEVKITPRO)/libnx/switch_rules

APP_TITLE	:=	Nazi Zombies Portable
APP_AUTHOR	:=	NZP Team
APP_VERSION	:=	2.0.0-indev
ICON        :=  source/platform/nx/art/icon.jpg

TARGET		:=	nzportable
BUILD		:=	build
SOURCES		:=	source
#DATA		:=	data
INCLUDES	:=	include
ICON		:= 	source/platform/nx/art/icon.jpg
#ROMFS		:=	romfs

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------
ARCH	:=	-march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE

CFLAGS	:=	-g -Wall -Wdouble-promotion -std=gnu99 -O3 \
			-fomit-frame-pointer -ffunction-sections \
			$(ARCH) $(DEFINES) `$(PREFIX)pkg-config --cflags SDL2_mixer`

CFLAGS	+=	$(INCLUDE) -DARM11 -D__SWITCH__ -DGLQUAKE -DPLATFORM_DIRECTORY="nx" -DPLATFORM_RENDERER="gl" \
			-DMAX_AI_COUNT=24 -DPLATFORM_CONFIRM_FLIPPED -DPLATFORM_KEYBOARD_SYSTEM \
			-DPLATFORM_INPUT_GAMEPAD

ifeq ($(WERROR),1)
CFLAGS 		+= -Werror
endif

ifeq ($(FANALYZER),1)
CFLAGS		+= -fanalyzer
endif

CXXFLAGS	:= $(CFLAGS) -fno-rtti -fno-exceptions -std=gnu++11

ASFLAGS	:=	-g $(ARCH)
LDFLAGS	=	-specs=$(DEVKITPRO)/libnx/switch.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)

LIBS	:=  `$(PREFIX)pkg-config --libs SDL2_mixer`

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:= $(PORTLIBS) $(LIBNX)


#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGET)
export TOPDIR	:=	$(CURDIR)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

COMMON_OBJS =	system.o \
				test_handler.c \
				chase.c \
                cl_hud.c \
				cl_demo.c \
				cl_input.c \
				cl_main.c \
				cl_parse.c \
				cl_tent.c \
				cl_slist.c \
				platform/nx/bsp_strlcpy.c \
				cmd.c \
				platform/nx/common.c \
				console.c \
				crc.c \
				cvar.c \
				host.c \
				host_cmd.c \
				keys.c \
				mathlib.c \
				matrixlib.c \
				menu/menu_sys.c \
				menu/menu.c \
				menu/menu_custommaps.c \
				menu/menu_helper.c \
				menu/menu_main.c \
				menu/menu_stockmaps.c \
				menu/menu_lobby.c \
				menu/menu_gamesettings.c \
				menu/menu_configuration.c \
				menu/menu_video.c \
				menu/menu_audio.c \
				menu/menu_controls.c \
				menu/menu_bindings.c \
				menu/menu_accessibility.c \
				menu/menu_pause.c \
				menu/menu_loadscreen.c \
				menu/menu_bios.c \
				menu/menu_credits.c \
				platform/nx/platform_menu.c \
				platform/nx/net_dgrm.c \
				platform/nx/net_udpnx.c \
				net_loop.c \
				platform/nx/net_bsd.c \
				platform/nx/net_main.c \
				net_vcr.c \
				pr_cmds.c \
				pr_edict.c \
				pr_exec.c \
				sv_main.c \
				sv_move.c \
				sv_phys.c \
				sv_user.c \
				view.c \
				wad.c \
				world.c \
				zone.c \
				platform/nx/sys_nx.c \
				snd_dma.c \
				snd_mix.c \
				snd_mem.c \
				images.c \
				platform/nx/snd_nx.c \
				input.c \
				platform/nx/in_nx.c \
				platform/nx/music_sdl.c \
				snd_music.c \
				platform/nx/gl/gl.c \
				platform/nx/gl/gl_qmb.c \
				platform/nx/gl/gl_decal.c \
				platform/nx/gl/gl_draw.c \
				render/r_fog.c \
		    	platform/nx/gl/gl_fog.c \
				platform/nx/gl/gl_mesh.c \
				platform/nx/gl/gl_model.c \
				render/r_entity_fragments.c \
				render/r_light.c \
				platform/nx/gl/gl_rmain.c \
				platform/nx/gl/gl_rmisc.c \
				platform/nx/gl/gl_rsurf.c \
				render/r_screen.c \
				platform/nx/gl/gl_warp.c \
				platform/nx/gl/gl_vidnx.c \
				platform/nx/r_part.c \
				crypter.c

CFILES		:=	$(COMMON_OBJS)
CPPFILES	:=	
SFILES		:=	
PICAFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.v.pica)))
SHLISTFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.shlist)))
#BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
#---------------------------------------------------------------------------------
	export LD	:=	$(CC)
#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
	export LD	:=	$(CXX)
#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------

export OFILES_SOURCES 	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)

export OFILES_BIN	:=	$(addsuffix .o,$(BINFILES)) \
			$(PICAFILES:.v.pica=.shbin.o) $(SHLISTFILES:.shlist=.shbin.o)

export OFILES := $(OFILES_BIN) $(OFILES_SOURCES)
export HFILES_BIN	:=	$(addsuffix .h,$(subst .,_,$(BINFILES)))

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
			$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
			-I$(CURDIR)/$(BUILD)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)

ifeq ($(strip $(CONFIG_JSON)),)
	jsons := $(wildcard *.json)
	ifneq (,$(findstring $(TARGET).json,$(jsons)))
		export APP_JSON := $(TOPDIR)/$(TARGET).json
	else
		ifneq (,$(findstring config.json,$(jsons)))
			export APP_JSON := $(TOPDIR)/config.json
		endif
	endif
else
	export APP_JSON := $(TOPDIR)/$(CONFIG_JSON)
endif

ifeq ($(strip $(ICON)),)
	icons := $(wildcard *.jpg)
	ifneq (,$(findstring $(TARGET).jpg,$(icons)))
		export APP_ICON := $(TOPDIR)/$(TARGET).jpg
	else
		ifneq (,$(findstring icon.jpg,$(icons)))
			export APP_ICON := $(TOPDIR)/icon.jpg
		endif
	endif
else
	export APP_ICON := $(TOPDIR)/$(ICON)
endif

ifeq ($(strip $(NO_ICON)),)
	export NROFLAGS += --icon=$(APP_ICON)
endif

ifeq ($(strip $(NO_NACP)),)
	export NROFLAGS += --nacp=$(CURDIR)/$(TARGET).nacp
endif

ifneq ($(APP_TITLEID),)
	export NACPFLAGS += --titleid=$(APP_TITLEID)
endif

ifneq ($(ROMFS),)
	export NROFLAGS += --romfsdir=$(CURDIR)/$(ROMFS)
endif

.PHONY: $(BUILD) clean all

#---------------------------------------------------------------------------------
all: _build_info.h $(BUILD)

_build_info.h:
	rm -rf $(CURDIR)/source/_build_info.h
	echo "#define GIT_HASH \"$(shell git rev-parse --short HEAD)$(shell git diff --quiet || echo -dirty)\"" > $(CURDIR)/source/_build_info.h
	echo "#define GIT_BRANCH \"$(shell git rev-parse --abbrev-ref HEAD)\"" >> $(CURDIR)/source/_build_info.h
	echo "#define BUILD_DATE \"$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")\"" >> $(CURDIR)/source/_build_info.h

$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@mkdir -p $(BUILD)/platform/nx
	@mkdir -p $(BUILD)/platform/nx/gl
	@mkdir -p $(BUILD)/menu
	@mkdir -p $(BUILD)/render
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.nx
	@mkdir -p $(BUILD)/nx
	@mkdir -p $(BUILD)/nx/bin/
	@mv $(BUILD)/*.o $(BUILD)/nx/
	@mv $(BUILD)/*.d $(BUILD)/nx/
	@mv $(BUILD)/platform/nx $(BUILD)/nx/
	@mv $(BUILD)/menu $(BUILD)/nx/
	@mv $(BUILD)/render $(BUILD)/nx/
	@mv $(BUILD)/$(TARGET).lst $(BUILD)/nx/
	@mv $(BUILD)/$(TARGET).map $(BUILD)/nx/
	@mv $(TARGET).* $(BUILD)/nx/bin/

#---------------------------------------------------------------------------------
clean:
	@echo clean ...
ifeq ($(strip $(APP_JSON)),)
	@rm -fr $(BUILD) $(TARGET).nro $(TARGET).nacp $(TARGET).elf
else
	@rm -fr $(BUILD) $(TARGET).nsp $(TARGET).nso $(TARGET).npdm $(TARGET).elf
endif


#---------------------------------------------------------------------------------
else
.PHONY:	all

DEPENDS	:=	$(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
ifeq ($(strip $(APP_JSON)),)

all	:	$(OUTPUT).nro

ifeq ($(strip $(NO_NACP)),)
$(OUTPUT).nro	:	$(OUTPUT).elf $(OUTPUT).nacp
else
$(OUTPUT).nro	:	$(OUTPUT).elf
endif

else

all	:	$(OUTPUT).nsp

$(OUTPUT).nsp	:	$(OUTPUT).nso $(OUTPUT).npdm

$(OUTPUT).nso	:	$(OUTPUT).elf

endif

$(OFILES_SOURCES) : $(HFILES)

$(OUTPUT).elf	:	$(OFILES)

#---------------------------------------------------------------------------------
# you need a rule like this for each extension you use as binary data
#---------------------------------------------------------------------------------
%.bin.o	%_bin.h :	%.bin
#---------------------------------------------------------------------------------
	@echo $(notdir $<)
	@$(bin2o)

-include $(DEPENDS)

#---------------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------------
