CROSS_COMPILE ?=
ifneq ($(strip $(CROSS_COMPILE)),)
ifeq ($(origin CC),default)
CC := $(CROSS_COMPILE)gcc
endif
endif
PKG_CONFIG ?= pkg-config

BUILD ?= build/sdl
TARGET ?= $(BUILD)/nzportable
DATA_DIR ?= build/data
CPPFLAGS := -Isource -I$(BUILD) -DGLQUAKE -DPLATFORM_SDL -DPLATFORM_CONFIRM_IS_ENTER \
			-DGL_SILENCE_DEPRECATION -DPLATFORM_DIRECTORY=sdl -DPLATFORM_RENDERER=gl \
			-DMAX_AI_COUNT=24 -DPLATFORM_USES_GENERIC_GLYPHS -DPLATFORM_SUPPORTS_HIGH_FRAMERATES \
			-DPLATFORM_SUPPORTS_VIDEO_OPTIONS
CFLAGS ?= -O2 -g
CFLAGS += -std=gnu99 -Wall -Wno-unused-variable -Wno-unused-but-set-variable $(shell $(PKG_CONFIG) --cflags sdl2 | sed 's/-Dmain=SDL_main//')
ifneq ($(findstring clang,$(shell $(CC) --version)),)
CFLAGS += -Wno-unknown-warning-option -Wno-unknown-pragmas
endif
ifeq ($(WERROR),1)
CFLAGS += -Werror
endif
LDLIBS := $(shell $(PKG_CONFIG) --libs sdl2) -lSDL2_mixer -lm
TARGET_TRIPLE := $(shell $(CC) -dumpmachine)
ifneq ($(findstring mingw,$(TARGET_TRIPLE)),)
LDLIBS += -static \
	-lopengl32 \
	-lglu32 \
	-lws2_32 \
	-lsetupapi \
	-lole32 \
	-loleaut32 \
	-limm32 \
	-lversion \
	-lcfgmgr32 \
	-lwinmm \
	-luuid
else ifeq ($(shell uname -s),Darwin)
LDLIBS += -framework OpenGL
else
LDLIBS += -lGL -lGLU
endif

ENGINE_SOURCES := $(wildcard source/*.c) $(wildcard source/menu/*.c) $(wildcard source/qcvm/*.c) $(wildcard source/render/*.c) $(wildcard source/tests/*.c)
SDL_SOURCES := $(wildcard source/platform/sdl/*.c) $(wildcard source/platform/sdl/gl/*.c)
SOURCES := $(ENGINE_SOURCES) $(SDL_SOURCES)
OBJECTS := $(patsubst source/%.c,$(BUILD)/%.o,$(SOURCES))

.PHONY: all clean run
all: $(TARGET)

$(BUILD)/_build_info.h:
	@mkdir -p $(@D)
	@{ echo '#define GIT_HASH "$(shell git rev-parse --short HEAD)$(shell git diff --quiet || echo -dirty)"'; \
	   echo '#define GIT_BRANCH "$(shell git rev-parse --abbrev-ref HEAD)"'; \
	   echo '#define BUILD_DATE "$(shell date -u +%Y-%m-%dT%H:%M:%SZ)"'; } > $@

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDLIBS) -o $@

$(BUILD)/%.o: source/%.c $(BUILD)/_build_info.h
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

run: $(TARGET)
	./$(TARGET) -basedir $(DATA_DIR)

clean:
	rm -rf $(BUILD)
