float4 main(
	float2 vTexcoord : TEXCOORD0,
	uniform float4 vColor,
	float4 coords : WPOS,
	uniform sampler2D tex,
	uniform float4 fogColor,
	uniform float fog_far,
	uniform float fog_range
	)
{	
	float4 c = tex2D(tex, vTexcoord) * vColor;
	
	float fog_dist = coords.z / coords.w;

	float vFog = (fog_far - fog_dist) / fog_range;
	vFog = clamp(vFog, 0.0f, 1.0f);
	c.rgb = lerp(fogColor.rgb, c.rgb, vFog);
	
	return c;
}
