float4 main(
	float2 vTexcoord : TEXCOORD0,
	float4 coords : WPOS,
	uniform sampler2D tex,
	uniform float4 fogColor,
	uniform float fog_far,
	uniform float fog_range
	)
{	
	float4 c = tex2D(tex, vTexcoord);
	
	float fog_dist = coords.z / coords.w;

	float vFog = (fog_far - fog_dist) / fog_range;
	vFog = clamp(vFog, 0.0f, 1.0f);
	c.rgb = lerp(c.rgb, fogColor.rgb, vFog);
	
	if (c.a > 0.666) return c;
	else discard;
}
