#ifndef _MENU_LOADTIPS_H_
#define _MENU_LOADTIPS_H_

static const char *const loading_tips[] =
{
    "Now with Font Kerning.",
    "Quick Revive will resurrect you in Solo.",
    "Use Quick Revive to revive faster in Co-Op!",
    "Jugger-Nog increases your health.",
    "Speed Cola increases Reload speed.",
    "Speed Cola allows faster Barricade building",
    "Double Tap will improve Rate of Fire.",
    "Stamin-Up increases your Move Speed.",
    "Stamin-Up allows you to Sprint longer.",
    "PhD Flopper grants explosive immunity.",
    "Dive-to-prone with PhD to cause PAIN!",
    "Deadshot Daiquiri improves your accuracy.",
    "Deadshot Daiquiri removes sniper scope sway.",
    "Deadshot Daiquiri increases weapon accuracy.",
    "Carry three weapons with Mule Kick!",
    "Removed Herobrine.",
    "Pack-A-Punch the Kar98k to get to round 500!",
    "NZ:P is on too many platforms to keep count of.",
    "Dive on top of your friends to win!",
    "Open Source!",
    "Max Ammo doesn't refill your mag, so RELOAD!",
    "KA-BOOM!",
    "NZ:P has been in development since 2009.",
    "Hold a crawler and hunt for secrets.",
    "'Where's the armor station?'",
    "https://docs.nzp.gay/",
    "Also try FreeCS by eukara!",
    "Also try FreeHL by eukara!",
    "FTE is a pretty awesome Quake sourceport",
	"Powered by VRIL-YA technology.",
    "\"your lg is nothink on the lan\" - Cooller",
    "\"¦]\" - Cooller",
    "\"i'm not your chaotic on dm6\" - Cooller",
    "\"alltimes lucky\" - Cooller",
    "\"not my trouble\" - Cooller",
    "\"it's not internet\" - Cooller",
    "\"relax\" - Cooller",
    "Also try LibreQuad.",
    "Support the Internet Archive!",
    "Don't write your menus in CSQC, trust me!",
    "Down with all that's good and clean...",
    "...And you can't fucking annihilate me!",
    "As seen on GamingOnLinux!",
    "Use the Zap-O-Matic if you need to revive in a pinch.",
    "Don't try to statically link OpenSSL in MinGW!",
    "As seen on YouTube!",
    "Now with less bugs!",
    "Free software!"
};

#endif // _MENU_LOADTIPS_H_
