void Menu_Start_Set(void);
void Menu_Main_Set(void);
void Menu_Paused_Set(void);
void Menu_SinglePlayer_Set(void);
void Menu_Options_Set(void);
void Menu_Keys_Set(void);
void Menu_Video_Set(void);
void Menu_Quit_Set(void);
void Menu_Restart_Set(void);
void Menu_Credits_Set(void);
void Menu_Exit_Set(void);
void Menu_GameOptions_Set(void);
void Menu_CustomMaps_Set(void);

void Menu_Start_Draw(void);
void Menu_Paused_Draw(void);
void Menu_Main_Draw(void);
void Menu_SinglePlayer_Draw(void);
void Menu_Options_Draw(void);
void Menu_Keys_Draw(void);
void Menu_Video_Draw(void);
void Menu_Quit_Draw(void);
void Menu_Restart_Draw(void);
void Menu_Credits_Draw(void);
void Menu_Exit_Draw(void);
void Menu_GameOptions_Draw(void);
void Menu_CustomMaps_Draw(void);

void Menu_Start_Key(int key);
void Menu_Paused_Key(int key);
void Menu_Main_Key(int key);
void Menu_SinglePlayer_Key(int key);
void Menu_Options_Key(int key);
void Menu_Keys_Key(int key);
void Menu_Restart_Key(int key);
void Menu_Credits_Key(int key);
void Menu_Video_Key(int key);
void Menu_Quit_Key(int key);
void Menu_Exit_Key(int key);
void Menu_GameOptions_Key(int key);
void Menu_CustomMaps_Key(int key);